2022-07-26 11:05:53 UTC | CORE | WARN | (pkg/util/log/log.go:591 in func1) | Deactivating Autoconfig will disable most components. It's recommended to use autoconfig_exclude_features and autoconfig_include_features to activate/deactivate features selectively
2022-07-26 11:05:53 UTC | CORE | INFO | (cmd/system-probe/config/config.go:118 in Merge) | no config exists at /etc/datadog-agent/system-probe.yaml, ignoring...
2022-07-26 11:05:53 UTC | CORE | INFO | (cmd/agent/app/status.go:125 in requestStatus) | Getting the status from the agent.
2022-07-26 11:05:58 UTC | CORE | INFO | (cmd/agent/app/status.go:163 in requestStatus) | 
===============
Agent (v7.38.0)
===============

  Status date: 2022-07-26 11:05:53.688 UTC (1658833553688)
  Agent start: 2022-07-26 11:04:33.051 UTC (1658833473051)
  Pid: 104
  Go Version: go1.17.11
  Python Version: 3.8.13
  Build arch: arm64
  Agent flavor: agent
  Check Runners: 4
  Log Level: debug

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 54.763ms
    System time: 2022-07-26 11:05:53.688 UTC (1658833553688)

  Host Info
  =========
    bootTime: 2022-07-22 04:54:51 UTC (1658465691000)
    hostId: 3914d834-2f19-4ce8-a034-3dcccf23a4e9
    kernelArch: aarch64
    kernelVersion: 5.10.104-linuxkit
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 11.4
    procs: 9
    uptime: 102h9m43s
    virtualizationRole: guest

  Hostnames
  =========
    hostname: 60e14b4f4552
    socket-fqdn: 60e14b4f4552
    socket-hostname: 60e14b4f4552
    hostname provider: os
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance and other providers already retrieve non-default hostnames
      azure: azure_hostname_style is set to 'os'
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: GCE metadata API error: Get "http://169.254.169.254/computeMetadata/v1/instance/hostname": dial tcp 169.254.169.254:80: connect: connection refused

  Metadata
  ========
    agent_version: 7.38.0
    config_apm_dd_url: 
    config_dd_url: 
    config_logs_dd_url: 
    config_logs_socks5_proxy_address: 
    config_no_proxy: []
    config_process_dd_url: 
    config_proxy_http: 
    config_proxy_https: 
    config_site: 
    feature_apm_enabled: true
    feature_cspm_enabled: false
    feature_cws_enabled: false
    feature_logs_enabled: true
    feature_networks_enabled: false
    feature_networks_http_enabled: false
    feature_networks_https_enabled: false
    feature_otlp_enabled: false
    feature_process_enabled: false
    feature_processes_container_enabled: true
    flavor: agent
    hostname_source: os
    install_method_installer_version: install_script-1.9.0
    install_method_tool: install_script
    install_method_tool_version: install_script
    logs_transport: HTTP

=========
Collector
=========

  Running Checks
  ==============

    apache (4.1.0)
    --------------
      Instance ID: apache:20d2bd531c0bd9c4 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/apache.d/conf.yaml
      Total Runs: 6
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 6
      Average Execution Time : 7ms
      Last Execution Date : 2022-07-26 11:05:50 UTC (1658833550000)
      Last Successful Execution Date : Never
      Error: 404 Client Error: Not Found for url: http://localhost/server-status?auto
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1120, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/apache/apache.py", line 91, in check
          r.raise_for_status()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
          raise HTTPError(http_error_msg, response=self)
      requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost/server-status?auto

    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 9, Total: 38
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-07-26 11:05:42 UTC (1658833542000)
      Last Successful Execution Date : 2022-07-26 11:05:42 UTC (1658833542000)


    disk (4.7.0)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 192, Total: 960
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 21ms
      Last Execution Date : 2022-07-26 11:05:49 UTC (1658833549000)
      Last Successful Execution Date : 2022-07-26 11:05:49 UTC (1658833549000)


    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 5, Total: 25
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-07-26 11:05:41 UTC (1658833541000)
      Last Successful Execution Date : 2022-07-26 11:05:41 UTC (1658833541000)


    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 28, Total: 122
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-07-26 11:05:48 UTC (1658833548000)
      Last Successful Execution Date : 2022-07-26 11:05:48 UTC (1658833548000)


    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 6, Total: 30
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-07-26 11:05:40 UTC (1658833540000)
      Last Successful Execution Date : 2022-07-26 11:05:40 UTC (1658833540000)


    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 20, Total: 100
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-07-26 11:05:47 UTC (1658833547000)
      Last Successful Execution Date : 2022-07-26 11:05:47 UTC (1658833547000)


    network (2.7.0)
    ---------------
      Instance ID: network:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 94, Total: 470
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 3ms
      Last Execution Date : 2022-07-26 11:05:39 UTC (1658833539000)
      Last Successful Execution Date : 2022-07-26 11:05:39 UTC (1658833539000)


    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 1
      Metric Samples: Last Run: 1, Total: 1
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 293ms
      Last Execution Date : 2022-07-26 11:04:35 UTC (1658833475000)
      Last Successful Execution Date : 2022-07-26 11:04:35 UTC (1658833475000)


    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 1, Total: 5
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-07-26 11:05:46 UTC (1658833546000)
      Last Successful Execution Date : 2022-07-26 11:05:46 UTC (1658833546000)

========
JMXFetch
========

  Information
  ==================
  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    Cluster: 0
    ClusterRole: 0
    ClusterRoleBinding: 0
    CronJob: 0
    DaemonSet: 0
    Deployment: 0
    Dropped: 0
    HighPriorityQueueFull: 0
    Ingress: 0
    Job: 0
    Node: 0
    PersistentVolume: 0
    PersistentVolumeClaim: 0
    Pod: 0
    ReplicaSet: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Role: 0
    RoleBinding: 0
    Service: 0
    ServiceAccount: 0
    StatefulSet: 0

  Transaction Successes
  =====================
    Total number: 12
    Successes By Endpoint:
      check_run_v1: 5
      intake: 2
      series_v1: 5

  On-disk storage
  ===============
    On-disk storage is disabled. Configure `forwarder_storage_max_size_in_bytes` to enable it.

  API Keys status
  ===============
    API key ending with 75019: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 75019

==========
Logs Agent
==========
    Reliable: Sending compressed logs in HTTPS to agent-http-intake.logs.datadoghq.com on port 443
    BytesSent: 0
    EncodedBytesSent: 0
    LogsProcessed: 0
    LogsSent: 0

  apache
  ------
    - Type: file
      Path: /var/log/access.log
      Status: Error: cannot read file /var/log/access.log: stat /var/log/access.log: no such file or directory
      BytesRead: 0
      Average Latency (ms): 0
      24h Average Latency (ms): 0
      Peak Latency (ms): 0
      24h Peak Latency (ms): 0


=============
Process Agent
=============

  Version: 7.38.0
  Status date: 2022-07-26 11:05:58.518 UTC (1658833558518)
  Process Agent Start: 2022-07-26 11:04:34.115 UTC (1658833474115)
  Pid: 128
  Go Version: go1.17.11
  Build arch: arm64
  Log Level: debug
  Enabled Checks: [process_discovery]
  Allocated Memory: 16,530,152 bytes
  Hostname: 60e14b4f4552

  =================
  Process Endpoints
  =================
    https://process.datadoghq.com - API Key ending with:
        - 75019

  =========
  Collector
  =========
    Last collection time: 2022-07-26 11:04:34
    Docker socket: 
    Number of processes: 0
    Number of containers: 0
    Process Queue length: 0
    RTProcess Queue length: 0
    Event Queue length: 0
    Pod Queue length: 0
    Process Bytes enqueued: 0
    RTProcess Bytes enqueued: 0
    Event Bytes enqueued: 0
    Pod Bytes enqueued: 0
    Drop Check Payloads: []

=========
APM Agent
=========
  Status: Running
  Pid: 152
  Uptime: 83 seconds
  Mem alloc: 9,845,288 bytes
  Hostname: 60e14b4f4552
  Receiver: localhost:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    No traces received in the previous minute.


  Writer (previous minute)
  ========================
    Traces: 0 payloads, 0 traces, 0 events, 0 bytes
    Stats: 0 payloads, 0 stats buckets, 0 bytes

==========
Aggregator
==========
  Checks Metric Sample: 1,845
  Dogstatsd Metric Sample: 777
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 5
  Series Flushed: 1,582
  Service Check: 54
  Service Checks Flushed: 55

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 776
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 68,730
  Udp Packet Reading Errors: 0
  Udp Packets: 452
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
  Unterminated Metric Errors: 0

====
OTLP
====

  Status: Not enabled
  Collector status: Not running

